#ifndef SCPS_MAP_DRESSING_H
#define SCPS_MAP_DRESSING_H
/*
 * scps_map_dressing.h — atlas de DÉCORS DE CARTE (pack « map dressing » étendu).
 *
 * Planche unique 512×512, cellules 32×32 (grille 16×16), fond MAGENTA 0xFF00FF
 * rendu transparent au chargement (colorkey SDL). VIEWER-ONLY (membrane : aucun
 * module moteur ne l'inclut — l'image est du rendu). DISPLAY-ONLY : le moteur et
 * le déterminisme n'y touchent jamais (même régime éditable que scps_lang.txt —
 * le binaire tourne sans le fichier ; ABSENT → carte lisse).
 *
 * 112 sprites en 7 FAMILLES de 8, variantes ORIGINALES (0-55) puis NOUVELLES
 * (56-111). Disposition compatible : id = ligne×16 + colonne. Noms calés sur le
 * manifeste livré (scps_map_dressing_assets_extended.csv).
 */

#define SCPS_MAP_DRESSING_FILE "scps_map_dressing.bmp"
#define SCPS_MAP_DRESSING_CELL 32
#define SCPS_MAP_DRESSING_COLS 16
#define SCPS_MAP_DRESSING_KEY_R 0xFF
#define SCPS_MAP_DRESSING_KEY_G 0x00
#define SCPS_MAP_DRESSING_KEY_B 0xFF
#define MAP_DRESSING_X(id) (((id) % SCPS_MAP_DRESSING_COLS) * SCPS_MAP_DRESSING_CELL)
#define MAP_DRESSING_Y(id) (((id) / SCPS_MAP_DRESSING_COLS) * SCPS_MAP_DRESSING_CELL)

typedef enum {
    /* — champs (fields) 0-7 — */
    MAPD_FIELD_WHEAT=0, MAPD_FIELD_TILLED, MAPD_FIELD_FENCED, MAPD_FIELD_ORCHARD,
    MAPD_FIELD_VINEYARD, MAPD_FIELD_HAY, MAPD_FIELD_PASTURE, MAPD_FIELD_MIXED,
    /* — bâtiments isolés (buildings) 8-15 — */
    MAPD_BLD_ROUND_HUT=8, MAPD_BLD_BARN, MAPD_BLD_WATCH_HUT, MAPD_BLD_WINDMILL,
    MAPD_BLD_WATERMILL, MAPD_BLD_CHAPEL, MAPD_BLD_STOREHOUSE, MAPD_BLD_MINE_SHACK,
    /* — arbres (trees) 16-23 — */
    MAPD_TREE_BROADLEAF=16, MAPD_TREES_BROADLEAF_CLUSTER, MAPD_TREE_CONIFER, MAPD_TREES_CONIFER_CLUSTER,
    MAPD_TREE_AUTUMN, MAPD_TREE_DEAD, MAPD_TREE_POPLAR, MAPD_GROVE_MIXED,
    /* — rochers (rocks) 24-31 — */
    MAPD_ROCK_BOULDER=24, MAPD_ROCKS_PAIR, MAPD_ROCKS_RIDGE, MAPD_ROCKS_SCREE,
    MAPD_ROCKS_ORE_DARK, MAPD_ROCKS_LIMESTONE, MAPD_ROCK_CLIFF_NUB, MAPD_ROCKS_MOSSY,
    /* — buissons / végétation basse (bushes) 32-39 — */
    MAPD_BUSH_GREEN=32, MAPD_BUSH_BERRY, MAPD_REEDS_CLUMP, MAPD_SCRUB_DRY,
    MAPD_BUSH_FLOWERING, MAPD_HEDGE_PATCH, MAPD_MARSH_GRASSES, MAPD_THICKET_LOW,
    /* — rivières (rivers) 40-47 — */
    MAPD_RIVER_STRAIGHT=40, MAPD_RIVER_BEND_GENTLE, MAPD_RIVER_BEND_SHARP, MAPD_RIVER_CONFLUENCE,
    MAPD_RIVER_FORK, MAPD_RIVER_MOUTH, MAPD_RIVER_FORD, MAPD_RIVER_BRIDGE,
    /* — routes (roads) 48-55 — */
    MAPD_ROAD_STRAIGHT=48, MAPD_ROAD_BEND, MAPD_ROAD_CROSS, MAPD_ROAD_T,
    MAPD_ROAD_FORK, MAPD_ROAD_STONE, MAPD_ROAD_MUDDY, MAPD_ROAD_BRIDGE,
    /* — nouvelles variantes (56-111) — */
    MAPD_FIELD_TERRACED=56, MAPD_FIELD_FLAX, MAPD_FIELD_PADDY, MAPD_FIELD_FALLOW,
    MAPD_FIELD_VEG_GARDEN, MAPD_FIELD_APIARY, MAPD_FIELD_ROCKY_POOR, MAPD_FIELD_SNOW_FROSTED,
    MAPD_BLD_COTTAGE=64, MAPD_BLD_FISHING_HUT, MAPD_BLD_LUMBER_CAMP, MAPD_BLD_QUARRY_SHED,
    MAPD_BLD_INN, MAPD_BLD_BOATHOUSE, MAPD_BLD_CHARCOAL_KILN, MAPD_BLD_SHEPHERD,
    MAPD_TREES_BIRCH=72, MAPD_TREE_OAK_LARGE, MAPD_TREES_PINE_SAPLINGS, MAPD_GROVE_THIN,
    MAPD_TREE_WIND_BENT, MAPD_TREE_SNOW_CONIFER, MAPD_TREE_DRY_SCRUB, MAPD_FOREST_CLUMP_DARK,
    MAPD_ROCKS_RED_SANDSTONE=80, MAPD_ROCKS_BASALT, MAPD_ROCKS_COPPER, MAPD_ROCKS_QUARTZ,
    MAPD_ROCKS_SHALE, MAPD_ROCK_MOSSY_LEDGE, MAPD_ROCKS_GRAVEL, MAPD_ROCKS_SNOW_CAPPED,
    MAPD_FERNS=88, MAPD_HEATHER, MAPD_DRY_THORN, MAPD_YELLOW_REEDS,
    MAPD_LILYPAD, MAPD_BERRY_THICKET, MAPD_TUNDRA_BRUSH, MAPD_WETLAND_SEDGE,
    MAPD_CREEK_STRAIGHT=96, MAPD_CREEK_BEND, MAPD_RIVER_RAPIDS, MAPD_RIVER_WATERFALL,
    MAPD_RIVER_DELTA, MAPD_RIVER_SWAMP_BEND, MAPD_RIVER_ICY, MAPD_CANAL,
    MAPD_FOOTPATH_STRAIGHT=104, MAPD_FOOTPATH_BEND, MAPD_ROAD_SWITCHBACK, MAPD_ROAD_STONE_BRIDGE,
    MAPD_ROAD_BOARDWALK, MAPD_ROAD_SNOW, MAPD_ROAD_DESERT, MAPD_ROAD_MILESTONE,
    MAPD_COUNT=112
} MapDressingSpriteId;

#endif /* SCPS_MAP_DRESSING_H */
