#ifndef SCPS_SPRITES_H
#define SCPS_SPRITES_H
/*
 * scps_sprites.h — LE CONTRAT DE LA PLANCHE (« contrat 184 »)
 *
 * Une planche unique 512×512, cellules 32×32 (grille 16×16), fond MAGENTA
 * 0xFF00FF rendu transparent au chargement (colorkey SDL). VIEWER-ONLY :
 * aucun module moteur n'inclut ce fichier (membrane — l'image est du rendu).
 *
 * Chargement : `scps_sprites.bmp` à côté du binaire ; ABSENT → g_sprite_tex==NULL
 * et le rendu actuel (glyphes vectoriels) reste tel quel. L'asset est DISPLAY-ONLY :
 * le moteur et le déterminisme n'y touchent jamais (même régime éditable que
 * scps_lang.txt — le binaire tourne sans le fichier).
 *
 * Les NOMS suivent la position dans la grille (id = ligne×16 + colonne).
 * La légende ci-dessous est calée sur la planche livrée ; si la légende
 * d'autorité diffère, corriger UNE ligne par sprite suffit (positionnel).
 */

#define SPRITE_CELL   32
#define SPRITE_COLS   16
#define SPRITE_SHEET_W (SPRITE_COLS*SPRITE_CELL)   /* 512 */
#define SPRITE_X(id)  (((id)%SPRITE_COLS)*SPRITE_CELL)
#define SPRITE_Y(id)  (((id)/SPRITE_COLS)*SPRITE_CELL)
#define SPRITE_RECT(id) (SDL_Rect){ SPRITE_X(id), SPRITE_Y(id), SPRITE_CELL, SPRITE_CELL }
#define SPRITE_KEY_R 0xFF
#define SPRITE_KEY_G 0x00
#define SPRITE_KEY_B 0xFF

typedef enum {
    /* ── ligne 0 : LES STATURES DE VILLE (G1.3) + l'anneau de capitale ───── */
    SPR_CITY_HAMEAU = 0, SPR_CITY_VILLAGE, SPR_CITY_BOURG, SPR_CITY_VILLE,
    SPR_CITY_CITE, SPR_CITY_METROPOLE, SPR_CITY_MEGAPOLE, SPR_CITY_CAPITALE,

    /* ── ligne 1 : RESSOURCES BRUTES ─────────────────────────────────────── */
    SPR_RAW_RES_GRAIN = 16, SPR_RAW_RES_POISSON, SPR_RAW_RES_BOIS,
    SPR_RAW_RES_PIERRE, SPR_RAW_RES_ARGILE, SPR_RAW_RES_FER,
    SPR_RAW_RES_CALCAIRE, SPR_RAW_RES_AMBRE, SPR_RAW_RES_HERBES,
    SPR_RAW_RES_BETAIL, SPR_RAW_RES_MOUTON, SPR_RAW_RES_RAISIN,
    SPR_RAW_RES_BAIES, SPR_RAW_RES_METAL, SPR_RAW_RES_GLACE, SPR_RAW_RES_OR,

    /* ── ligne 2 : BIENS PRODUITS ────────────────────────────────────────── */
    SPR_PROD_ETOFFE = 32, SPR_PROD_OUTILS, SPR_PROD_PAPIER, SPR_PROD_BIERE,
    SPR_PROD_VIN, SPR_PROD_REMEDE, SPR_PROD_TEINTURE, SPR_PROD_ETOFFE_PRECIEUSE,
    SPR_PROD_SAC, SPR_PROD_MORTIER, SPR_PROD_CHAINE, SPR_PROD_TONNEAU,
    SPR_PROD_PARCHEMIN, SPR_PROD_SEL, SPR_PROD_LINGOT, SPR_PROD_JOYAU,

    /* ── ligne 3 : ACTIONS & VERBES (sidebar/diplo) ──────────────────────── */
    SPR_ACT_GUERRE = 48, SPR_ACT_PAIX, SPR_ACT_COLONISER, SPR_ACT_REVENDIQUER,
    SPR_ACT_BATIR, SPR_ACT_AGENT, SPR_ACT_MONUMENT, SPR_ACT_OR,
    SPR_ACT_GEMMES, SPR_ACT_ALCHIMIE, SPR_ACT_NAVIRE, SPR_ACT_PEUPLE,
    SPR_ACT_PACTE, SPR_ACT_ROUAGE,

    /* ── ligne 4 : STATUTS (bandeaux/chips) ──────────────────────────────── */
    SPR_STATUS_DEFENSE = 64, SPR_STATUS_GARDE, SPR_STATUS_SOLEIL,
    SPR_STATUS_COURONNE, SPR_STATUS_ARCANE, SPR_STATUS_BALANCE,
    SPR_STATUS_ALLIANCE, SPR_STATUS_GUERRE, SPR_STATUS_BOUCLIER,
    SPR_STATUS_BANNIERE, SPR_STATUS_REVOLTE, SPR_STATUS_FAMINE,
    SPR_STATUS_PLAGUE, SPR_STATUS_FEU, SPR_STATUS_OK,

    /* ── ligne 5 : ÉDIFICES ÉCONOMIQUES & CIVIQUES ───────────────────────── */
    SPR_BLDG_MARCHE = 80, SPR_BLDG_COMPTOIR, SPR_BLDG_BANQUE, SPR_BLDG_CHATEAU,
    SPR_BLDG_HALLE, SPR_BLDG_REGISTRE, SPR_BLDG_TRIBUNAL, SPR_BLDG_TEMPLE,
    SPR_BLDG_PORT, SPR_BLDG_EAU, SPR_BLDG_PUITS, SPR_BLDG_JUSTICE,
    SPR_BLDG_APOTHICAIRE,

    /* ── ligne 6 : LES FORKS (arc M, §9) — hovers SPR_BLDG_FORK_* ────────── */
    SPR_BLDG_FORK_ARSENAL = 96, SPR_BLDG_FORK_AMIRAUTE, SPR_BLDG_FORK_PORT_MARCHAND,
    SPR_BLDG_FORK_BIBLIO_MIL, SPR_BLDG_FORK_OBSERVATOIRE, SPR_BLDG_FORK_CONSEIL_GUERRE,
    SPR_BLDG_FORK_GUILDE, SPR_BLDG_FORK_DONJON, SPR_BLDG_FORK_REMPART,

    /* ── lignes 7-9 : UNITÉS (spine + doctrines, §11-12) ─────────────────── */
    SPR_UNIT_PIQUIER = 112, SPR_UNIT_LANCIER, SPR_UNIT_EPEISTE, SPR_UNIT_ARCHER,
    SPR_UNIT_ARBALETE, SPR_UNIT_CAV_LEGERE, SPR_UNIT_CAV_LOURDE, SPR_UNIT_MAGE,
    SPR_UNIT_HALLEBARDIER = 128, SPR_UNIT_FOUDRIER, SPR_UNIT_ARBALETRIER_LOURD,
    SPR_UNIT_BERSERKER, SPR_UNIT_LANCIER_CHOC, SPR_UNIT_CAV_CUIRASSEE,
    SPR_UNIT_CAV_RAID, SPR_UNIT_CHAMAN,
    SPR_UNIT_HARCELEUR = 144, SPR_UNIT_TRAQUEUR, SPR_UNIT_MILICE,
    SPR_UNIT_LAME_FRANCHE, SPR_UNIT_GARDE_ESCORTE, SPR_UNIT_CAV_RAPIDE,
    SPR_UNIT_SORCIER, SPR_UNIT_ALCHIMISTE,

    /* ── ligne 10 : RESSOURCES RARES & ARCANES — hovers SPR_RARE_RES_* ───── */
    SPR_RARE_RES_CRISTAL = 160, SPR_RARE_RES_AMETHYSTE, SPR_RARE_RES_ESSENCE,
    SPR_RARE_RES_ESSENCE_PURIFIEE, SPR_RARE_RES_INDIGO, SPR_RARE_RES_ENCENS,
    SPR_RARE_RES_MUREX, SPR_RARE_RES_SALPETRE,

    /* ── ligne 11 : VISAGES & HUMEURS (survols) ──────────────────────────── */
    SPR_FACE_CONTENT = 176, SPR_FACE_NEUTRE, SPR_FACE_GRONDE, SPR_FACE_REVOLTE,
    SPR_FACE_CONSEIL, SPR_FACE_EPEE, SPR_FACE_OR, SPR_FACE_MASQUE,
    SPR_FACE_COFFRE, SPR_FACE_GARDE, SPR_FACE_FOULE,

    /* ── ligne 12 : SOUCHES (portraits, §2) ──────────────────────────────── */
    SPR_RACE_HUMAIN = 192, SPR_RACE_ELFE, SPR_RACE_NAIN, SPR_RACE_ORQUE,
    SPR_RACE_HALFELIN, SPR_RACE_GNOME, SPR_RACE_BETE,

    /* ── ligne 13 : BIOMES (tuiles rondes) ───────────────────────────────── */
    SPR_BIOME_0 = 208,   /* …+15 : l'ordre suit l'enum Biome du moteur */

    /* ── ligne 14 : ÉVÉNEMENTS (les 14 du directeur + géo) ───────────────── */
    SPR_EVT_FAMINE = 224, SPR_EVT_PESTE, SPR_EVT_RITE, SPR_EVT_GUERRE,
    SPR_EVT_FOULE, SPR_EVT_SECHERESSE, SPR_EVT_INONDATION, SPR_EVT_ERUPTION,
    SPR_EVT_EDIT, SPR_EVT_FOUDRE, SPR_EVT_PRESAGE, SPR_EVT_COMETE,

    /* ── ligne 15 : TECH & DIVERS ────────────────────────────────────────── */
    SPR_TECH_FORGE = 240, SPR_TECH_ROUE, SPR_TECH_DECRET, SPR_TECH_COMPTE,
    SPR_TECH_SIMPLES, SPR_TECH_ASTRONOMIE, SPR_TECH_TOMBE, SPR_TECH_CALENDRIER,
    SPR_TECH_ALCHIMIE,

    SPR_COUNT = 256
} SpriteId;

#endif /* SCPS_SPRITES_H */
