#ifndef SCPS_MAP_NATURE_SPRITES_H
#define SCPS_MAP_NATURE_SPRITES_H

/* Optional display-only atlas for map nature decals.
 * Not part of simulation. Safe to omit at runtime.
 */

#define SCPS_MAP_NATURE_FILE "scps_map_nature_sprites.bmp"
#define SCPS_MAP_NATURE_CELL 32
#define SCPS_MAP_NATURE_COLS 16
#define SCPS_MAP_NATURE_ROWS 16
#define SCPS_MAP_NATURE_KEY_R 0xFF
#define SCPS_MAP_NATURE_KEY_G 0x00
#define SCPS_MAP_NATURE_KEY_B 0xFF

#define MAP_NATURE_X(id) (((id) % SCPS_MAP_NATURE_COLS) * SCPS_MAP_NATURE_CELL)
#define MAP_NATURE_Y(id) (((id) / SCPS_MAP_NATURE_COLS) * SCPS_MAP_NATURE_CELL)

typedef enum {
    MAP_NAT_TREE_PINE_SMALL = 0,
    MAP_NAT_TREE_PINE_PAIR,
    MAP_NAT_TREE_BROADLEAF_SMALL,
    MAP_NAT_TREE_BROADLEAF_CLUSTER,
    MAP_NAT_TREE_OAK_DARK,
    MAP_NAT_TREE_DEAD,
    MAP_NAT_TREE_PALM,
    MAP_NAT_TREE_MANGROVE,
    MAP_NAT_TREE_STUMP,
    MAP_NAT_BUSH_SMALL,
    MAP_NAT_BUSH_CLUSTER,
    MAP_NAT_FOREST_SHADOW,
    MAP_NAT_JUNGLE_CLUSTER,
    MAP_NAT_SNOW_PINE,
    MAP_NAT_ORCHARD_SMALL,
    MAP_NAT_GRASS_TUFT,

    MAP_NAT_REEDS_SINGLE = 16,
    MAP_NAT_REEDS_CLUSTER,
    MAP_NAT_REEDS_TALL,
    MAP_NAT_CATTAILS,
    MAP_NAT_WATERGRASS,
    MAP_NAT_LILY_PAD,
    MAP_NAT_MARSH_PUDDLE,
    MAP_NAT_BOG_MOUND,
    MAP_NAT_MANGROVE_ROOTS,
    MAP_NAT_SWAMP_TREE,
    MAP_NAT_WET_SPECKLES,
    MAP_NAT_MARSH_CLUSTER_A,
    MAP_NAT_MARSH_CLUSTER_B,
    MAP_NAT_REED_BANK_HORIZONTAL,
    MAP_NAT_REED_BANK_VERTICAL,
    MAP_NAT_SMALL_POND,

    MAP_NAT_RIVER_THIN_VERTICAL = 32,
    MAP_NAT_RIVER_THIN_HORIZONTAL,
    MAP_NAT_RIVER_THIN_DIAG_NE,
    MAP_NAT_RIVER_THIN_DIAG_NW,
    MAP_NAT_RIVER_WIDE_VERTICAL,
    MAP_NAT_RIVER_WIDE_HORIZONTAL,
    MAP_NAT_RIVER_BEND_NE,
    MAP_NAT_RIVER_BEND_NW,
    MAP_NAT_RIVER_FORK,
    MAP_NAT_RIVER_DELTA,
    MAP_NAT_RIVER_RAPIDS,
    MAP_NAT_RIVER_SHIMMER,
    MAP_NAT_SHORE_WET_EDGE,
    MAP_NAT_LAKE_EDGE_A,
    MAP_NAT_LAKE_EDGE_B,
    MAP_NAT_FORD,

    MAP_NAT_ROCK_SMALL = 48,
    MAP_NAT_ROCK_CLUSTER,
    MAP_NAT_HILL_BUMP,
    MAP_NAT_HILL_CLUSTER,
    MAP_NAT_MOUNTAIN_SMALL,
    MAP_NAT_MOUNTAIN_PEAK,
    MAP_NAT_MOUNTAIN_SNOW,
    MAP_NAT_CLIFF_FACE,
    MAP_NAT_SCREE,
    MAP_NAT_VOLCANIC_ROCK,
    MAP_NAT_VOLCANO_CONE,
    MAP_NAT_CAVE_DARK,
    MAP_NAT_HIGHLAND_GRASS,
    MAP_NAT_ICE_ROCKS,
    MAP_NAT_DESERT_STONES,
    MAP_NAT_MINERAL_SPARK,

    MAP_NAT_COAST_FOAM_SMALL = 64,
    MAP_NAT_COAST_FOAM_LONG,
    MAP_NAT_COAST_FOAM_CURVE,
    MAP_NAT_COAST_ROCKS,
    MAP_NAT_WAVELETS_A,
    MAP_NAT_WAVELETS_B,
    MAP_NAT_CURRENT_MARK_E,
    MAP_NAT_CURRENT_MARK_W,
    MAP_NAT_CURRENT_MARK_N,
    MAP_NAT_CURRENT_MARK_S,
    MAP_NAT_SHOAL_PATCH,
    MAP_NAT_DEEP_WATER_SPARK,
    MAP_NAT_DEAD_WATER_SPECK,
    MAP_NAT_COASTAL_SAND,
    MAP_NAT_ICE_FLOE,
    MAP_NAT_STORM_CHOP
} MapNatureSpriteId;

#endif /* SCPS_MAP_NATURE_SPRITES_H */
